const mongoose = require('mongoose'), 
    Schema = mongoose.Schema;

const studentSchema = new Schema({
    loginRole: {type: String, default: 'PLACEHOLDER'},
    loginEmail: {type: String, default: 'PLACEHOLDER'},
    loginPassword: {type: String, default: 'PLACEHOLDER'},
    updated_at : Date,
    created_at : Date,
    survey: {
        demoAge: {type: String},
        gender: {type: String},
        //genderOther: {type: String},
        ethnicity: {type: String},
        //ethnicityOther: {type: String},
        institution: {type: String},
        enrollStatus: {type: String},
        collegeYear: {type: String},
        beforeFirstSemester: {type: String},
        //beforeFirstSemesterOther: {type: String},
        major: {type: String},
        field: {type: String, default: ''},
        //fieldOther: {type: String, default: ''},
        switchFromStem: {type: String, default: ''},
        intendToSwitch: {type: String, default: ''},
        intendedMajor: {type: String, default: ''},
        involvedInActivity: {type: String, default: ''},
        intendedActivity: {type: String, default: ''},
        no_OCA_1to14: {
            //default: [],
            noOCAReason1: {type: String, default: ""},
            noOCAReason2: {type: String, default: ""},
            noOCAReason3: {type: String, default: ""},
            noOCAReason4: {type: String, default: ""},
            noOCAReason5: {type: String, default: ""},
            noOCAReason6: {type: String, default: ""},
            noOCAReason7: {type: String, default: ""},
            noOCAReason8: {type: String, default: ""},
            noOCAReason9: {type: String, default: ""},
            noOCAReason10: {type: String, default: ""},
            noOCAReason11: {type: String, default: ""},
            noOCAReason12: {type: String, default: ""},
            noOCAReason13: {type: String, default: ""},
            noOCAReason14: {type: String, default: ""}
        },
        noOCA_15to30: {
            //default: [],
            noOCAReason15: {type: String, default: ''},
            noOCAReason16: {type: String, default: ''},
            noOCAReason17: {type: String, default: ''},
            noOCAReason18: {type: String, default: ''},
            noOCAReason19: {type: String, default: ''},
            noOCAReason20: {type: String, default: ''},
            noOCAReason21: {type: String, default: ''},
            noOCAReason22: {type: String, default: ''},
            noOCAReason23: {type: String, default: ''},
            noOCAReason24: {type: String, default: ''},
            noOCAReason25: {type: String, default: ''},
            noOCAReason26: {type: String, default: ''},
            noOCAReason27: {type: String, default: ''},
            noOCAReason28: {type: String, default: ''},
            noOCAReason29: {type: String, default: ''},
            noOCAReason30: {type: String, default: ''}
        },
        ae_grit: {
            ae1: {type: String},
            ae2: {type: String},
            ae3: {type: String},
            ae4: {type: String},
            ae5: {type: String},
            ae6: {type: String},
            ae7: {type: String},
            ae8: {type: String},
            ae9: {type: String},
            ae10: {type: String},
            ae11: {type: String},
            ae12: {type: String},
            ae13: {type: String},
            ae14: {type: String},
            ae15: {type: String},
            ae16: {type: String},
            ae17: {type: String},
            ae18: {type: String},
            ae19: {type: String},
            ae20: {type: String},
            ae21: {type: String},
            ae22: {type: String},
            ae23: {type: String},
            ae24: {type: String},
            ae25: {type: String},
            ae26: {type: String},
            ae27: {type: String},
            ae28: {type: String},
            grit1: {type: String},
            grit2: {type: String},
            grit3: {type: String},
            grit4: {type: String},
            grit5: {type: String},
            grit6: {type: String},
            grit7: {type: String},
            grit8: {type: String}
        },

        livingArea: {type: String},
        //livingAreaOther: {type: String},
        gpa: {
            firstYearGPA: {type: String, default: 'N/A'},
            cumulativeGPA: {type: String, default: '999'},
            maxGPA: {type: String, default: '999'}
        },
        guardian1: {type: String},
        //guardian1_notRelated: {type: String},
        guardian2: {type: String},
        //guardian2_notRelated: {type: String},
        parentEducation: {
            guardian1SchoolLevel: {type: String},
            guardian2SchoolLevel: {type: String}
        },
        siblingCompleteDegree: {type: String},
        houseIncome: {type: String},
        usCitizen: {type: String},
        military: {type: String},
        disability: {type: String},
        //disability_other: {type: String},
        lgbt: {type: String},
        highschool1: {type: String, default: ''},
        highschool2: {type: String, default: ''},
        highschool3: {type: String, default: ''},
        highschool4: {type: String, default: ''},
        highschool5: {type: String, default: ''},
        highschool6: {type: String, default: ''},
        contact1: {type: String, default: ''},
        contact2: {type: String, default: ''},
        contactInfo: {
            default: [],
            contact3: {type: String, default: ''},
            contact4: {type: String, default: ''},
            contact5: {type: String, default: ''}
        },
        contact6: {type: String, default: ''},
        all: {type: Array, default: []},
        //allOther: {type: Array},
        levelAct: {
            //default: [],
            levelAct1: {type: String, default: ''},
            levelAct2: {type: String, default: ''},
            levelAct3: {type: String, default: ''},
            levelAct4: {type: String, default: ''},
            levelAct5: {type: String, default: ''},
            levelAct6: {type: String, default: ''},
            levelAct7: {type: String, default: ''},
            levelAct8: {type: String, default: ''},
            levelAct9: {type: String, default: ''},
            levelAct10: {type: String, default: ''},
            levelAct11: {type: String, default: ''},
            levelAct12: {type: String, default: ''},
            levelAct13: {type: String, default: ''},
            levelAct14: {type: String, default: ''},
            levelAct15: {type: String, default: ''},
            levelAct16: {type: String, default: ''},
            levelAct17: {type: String, default: ''},
            levelAct18: {type: String, default: ''},
            levelAct19: {type: String, default: ''},
            levelAct20: {type: String, default: ''}
        },
        participationHours: {type: String, default: ''},
        participationCredit: {type: String, default: ''},
        participationPaid: {type: String, default: ''},
        allOut: {
            //default: [],
            allOut1: {type: String, default: ''},
            allOut2: {type: String, default: ''},
            allOut3: {type: String, default: ''},
            allOut4: {type: String, default: ''},
            allOut5: {type: String, default: ''},
            allOut6: {type: String, default: ''},
            allOut7: {type: String, default: ''},
            allOut8: {type: String, default: ''},
            allOut9: {type: String, default: ''},
            allOut10: {type: String, default: ''},
            allOut11: {type: String, default: ''},
            allOut12: {type: String, default: ''},
            allOut13: {type: String, default: ''},
            allOut14: {type: String, default: ''},
            allOut15: {type: String, default: ''},
            allOut16: {type: String, default: ''},
            allOut17: {type: String, default: ''},
            allOut18: {type: String, default: ''},
            allOut19: {type: String, default: ''},
            allOut20: {type: String, default: ''},
            allOut21: {type: String, default: ''},
            allOut22: {type: String, default: ''},
            allOut23: {type: String, default: ''},
            allOut24: {type: String, default: ''},
            allOut25: {type: String, default: ''},
            allOut26: {type: String, default: ''},
            allOut27: {type: String, default: ''},
            allOut28: {type: String, default: ''},
            allOut29: {type: String, default: ''},
            allOut30: {type: String, default: ''}
        },
        allReason_1to14: {
            //default: [],
            allReason1: {type: String, default: ''},
            allReason2: {type: String, default: ''},
            allReason3: {type: String, default: ''},
            allReason4: {type: String, default: ''},
            allReason5: {type: String, default: ''},
            allReason6: {type: String, default: ''},
            allReason7: {type: String, default: ''},
            allReason8: {type: String, default: ''},
            allReason9: {type: String, default: ''},
            allReason10: {type: String, default: ''},
            allReason11: {type: String, default: ''},
            allReason12: {type: String, default: ''},
            allReason13: {type: String, default: ''},
            allReason14: {type: String, default: ''}
        },
        allReason_15to30: {
            //default: [],
            allReason15: {type: String, default: ''},
            allReason16: {type: String, default: ''},
            allReason17: {type: String, default: ''},
            allReason18: {type: String, default: ''},
            allReason19: {type: String, default: ''},
            allReason20: {type: String, default: ''},
            allReason21: {type: String, default: ''},
            allReason22: {type: String, default: ''},
            allReason23: {type: String, default: ''},
            allReason24: {type: String, default: ''},
            allReason25: {type: String, default: ''},
            allReason26: {type: String, default: ''},
            allReason27: {type: String, default: ''},
            allReason28: {type: String, default: ''},
            allReason29: {type: String, default: ''},
            allReason30: {type: String, default: ''}
        },
        top: {type: String},
        topOut: {
            default: [],
            topOut1: {type: String, default: ''},
            topOut2: {type: String, default: ''},
            topOut3: {type: String, default: ''},
            topOut4: {type: String, default: ''},
            topOut5: {type: String, default: ''},
            topOut6: {type: String, default: ''},
            topOut7: {type: String, default: ''},
            topOut8: {type: String, default: ''},
            topOut9: {type: String, default: ''},
            topOut10: {type: String, default: ''},
            topOut11: {type: String, default: ''},
            topOut12: {type: String, default: ''},
            topOut13: {type: String, default: ''},
            topOut14: {type: String, default: ''},
            topOut15: {type: String, default: ''},
            topOut16: {type: String, default: ''},
            topOut17: {type: String, default: ''},
            topOut18: {type: String, default: ''},
            topOut19: {type: String, default: ''},
            topOut20: {type: String, default: ''},
            topOut21: {type: String, default: ''},
            topOut22: {type: String, default: ''},
            topOut23: {type: String, default: ''},
            topOut24: {type: String, default: ''},
            topOut25: {type: String, default: ''},
            topOut26: {type: String, default: ''},
            topOut27: {type: String, default: ''},
            topOut28: {type: String, default: ''},
            topOut29: {type: String, default: ''},
            topOut30: {type: String, default: ''}
        },
        topReason: {
            //default: [],
            topReason1: {type: String, default: ''},
            topReason2: {type: String, default: ''},
            topReason3: {type: String, default: ''},
            topReason4: {type: String, default: ''},
            topReason5: {type: String, default: ''},
            topReason6: {type: String, default: ''},
            topReason7: {type: String, default: ''},
            topReason8: {type: String, default: ''},
            topReason9: {type: String, default: ''},
            topReason10: {type: String, default: ''},
            topReason11: {type: String, default: ''},
            topReason12: {type: String, default: ''},
            topReason13: {type: String, default: ''},
            topReason14: {type: String, default: ''}
        }
/*
        activities: {type: Array},
        weekHr: {type: Number},
        MajorSatisfaction1: {type: String},
        MajorSatisfaction2: {type: String},
        MajorSatisfaction3: {type: String},
        MajorSatisfaction4: {type: String},
        MajorSatisfaction5: {type: String},
        Belonging1: {type: String},
        Belonging2: {type: String},
        Belonging3: {type: String},
        MajorValuing1: {type: String},
        MajorValuing2: {type: String},
        MajorValuing3: {type: String},
        AchievementStriving1: {type: String},
        AchievementStriving2: {type: String},
        AchievementStriving3: {type: String},
        AchievementStriving4: {type: String},
        AchievementStriving5: {type: String},
        PosFalRelationship1: {type: String},
        PosFalRelationship2: {type: String},
        PosFalRelationship3: {type: String},
        PeerInteraction1: {type: String},
        PeerInteraction2: {type: String},
        PeerInteraction3: {type: String},
        PeerInteraction4: {type: String},
        Grit1: {type: String},
        Grit2: {type: String},
        Grit3: {type: String},
        Grit4: {type: String},
        Grit5: {type: String},
        Grit6: {type: String},
        Grit7: {type: String},
        Grit8: {type: String},
        topActivity: {type: String},
        E2: {type: Number},
        E3: {type: Number},
        E4: {type: Number},
        E5: {type: Number},
        E6: {type: Number},
        E7: {type: Number},
        E8: {type: Number},
        E9: {type: Number},
        phone: {type: String}*/
    }
});

// Before saving student into database, updates the updated_at and created_at (if student is new) 
studentSchema.pre('save', function(next) {
    const currentDate = new Date();
    this.updated_at = currentDate;
    if(!this.created_at){
      this.created_at = currentDate;
    }
    next();
});

const Student = mongoose.model('Student', studentSchema);

module.exports = Student;


