const mongoose = require('mongoose'), 
    Schema = mongoose.Schema;

const studentSchema = new Schema({
    /*
    email: {
        type: String,
        trim: true,
        unique: true,
        required: true
    },
    password: {
        type: String,
        required: true
    },
    updated_at : Date,
    created_at : Date,
    survey: {
        age:    {type: Number},
        gender: {type: String},
        raceEthnicity: {type: String},
        enrollStatus: {type: String},
        collegeYear: {type: String},
        major: {type: String},
        activities: {type: Array},
        weekHr: {type: Number},
        MajorSatisfaction1: {type: String},
        MajorSatisfaction2: {type: String},
        MajorSatisfaction3: {type: String},
        MajorSatisfaction4: {type: String},
        MajorSatisfaction5: {type: String},
        Belonging1: {type: String},
        Belonging2: {type: String},
        Belonging3: {type: String},
        MajorValuing1: {type: String},
        MajorValuing2: {type: String},
        MajorValuing3: {type: String},
        AchievementStriving1: {type: String},
        AchievementStriving2: {type: String},
        AchievementStriving3: {type: String},
        AchievementStriving4: {type: String},
        AchievementStriving5: {type: String},
        PosFalRelationship1: {type: String},
        PosFalRelationship2: {type: String},
        PosFalRelationship3: {type: String},
        PeerInteraction1: {type: String},
        PeerInteraction2: {type: String},
        PeerInteraction3: {type: String},
        PeerInteraction4: {type: String},
        Grit1: {type: String},
        Grit2: {type: String},
        Grit3: {type: String},
        Grit4: {type: String},
        Grit5: {type: String},
        Grit6: {type: String},
        Grit7: {type: String},
        Grit8: {type: String},
        topActivity: {type: String},
        E2: {type: Number},
        E3: {type: Number},
        E4: {type: Number},
        E5: {type: Number},
        E6: {type: Number},
        E7: {type: Number},
        E8: {type: Number},
        E9: {type: Number},
        phone: {type: String}
    }
    */
   email: {
    type: String,
    trim: true,
    //unique: true,
    //required: true
    },
    updated_at : Date,
    created_at : Date,
    survey: {
        demoAge:    {type: Number},
        gender: {type: String},
        genderOther: {type: String},
        ethnicity: {type: String},
        ethnicityOther: {type: String},
        enrollStatus: {type: String},
        collegeYear: {type: String},
        beforeFirstSemester: {type: String},
        beforeFirstSemesterOther: {type: String},
        major: {type: String},
        field: {type: String},
        fieldOther: {type: String},
        switchFromStem: {type: String},
        intendToSwitch: {type: String},
        intendedMajor: {type: String},
        noOCAReason1: {type: String},
        noOCAReason2: {type: String},
        noOCAReason3: {type: String},
        noOCAReason4: {type: String},
        noOCAReason5: {type: String},
        noOCAReason6: {type: String},
        noOCAReason7: {type: String},
        noOCAReason8: {type: String},
        noOCAReason9: {type: String},
        noOCAReason10: {type: String},
        noOCAReason11: {type: String},
        noOCAReason12: {type: String},
        noOCAReason13: {type: String},
        noOCAReason14: {type: String},
        noOCAReason15: {type: String},
        noOCAReason16: {type: String},
        noOCAReason17: {type: String},
        noOCAReason18: {type: String},
        noOCAReason19: {type: String},
        noOCAReason20: {type: String},
        noOCAReason21: {type: String},
        noOCAReason22: {type: String},
        noOCAReason23: {type: String},
        noOCAReason24: {type: String},
        noOCAReason25: {type: String},
        noOCAReason26: {type: String},
        noOCAReason27: {type: String},
        noOCAReason28: {type: String},
        noOCAReason29: {type: String},
        noOCAReason30: {type: String},
        ae1: {type: String},
        ae2: {type: String},
        ae3: {type: String},
        ae4: {type: String},
        ae5: {type: String},
        ae6: {type: String},
        ae7: {type: String},
        ae8: {type: String},
        ae9: {type: String},
        ae10: {type: String},
        ae11: {type: String},
        ae12: {type: String},
        ae13: {type: String},
        ae14: {type: String},
        ae15: {type: String},
        ae16: {type: String},
        ae17: {type: String},
        ae18: {type: String},
        ae19: {type: String},
        ae20: {type: String},
        ae21: {type: String},
        ae22: {type: String},
        ae23: {type: String},
        ae24: {type: String},
        ae25: {type: String},
        ae26: {type: String},
        ae27: {type: String},
        ae28: {type: String},
        grit1: {type: Number},
        grit2: {type: Number},
        grit3: {type: Number},
        grit4: {type: Number},
        grit5: {type: Number},
        grit6: {type: Number},
        grit7: {type: Number},
        grit8: {type: Number},
        livingArea: {type: String},
        livingAreaOther: {tpye: String},
        firstYearGPA: {type: Number},
        cumulativeGPA: {type: Number},
        maxGPA: {type: Number},
        guardian1: {type: String},
        guardian1_notRelated: {type: String},
        guardian2: {type: String},
        guardian2_notRelated: {type: String},
        guardian1SchoolLevel: {type: String},
        guardian2SchoolLevel: {type: String},
        siblingCompleteDegree: {type: String},
        houseIncome: {type: String},
        usCitizen: {type: String},
        military: {type: String},
        disability: {type: String},
        disability_other: {type: String},
        lgbt: {type: String},
        highshcool1: {type: String},
        highshcool2: {type: String},
        highshcool3: {type: Number},
        highshcool4: {type: String},
        highshcool5: {type: Number},
        highshcool6: {type: String},
        contact1: {type: String},
        contact2: {type: String},
        contact3: {type: String},
        contact4: {type: String},
        contact5: {type: String},
        contact6: {type: String},
        all: {type: Array},
        allOther: {type: Array},
        levelAct1: {type: String},
        levelAct2: {type: String},
        levelAct3: {type: String},
        levelAct4: {type: String},
        levelAct5: {type: String},
        levelAct6: {type: String},
        levelAct7: {type: String},
        levelAct8: {type: String},
        levelAct9: {type: String},
        levelAct10: {type: String},
        levelAct11: {type: String},
        levelAct12: {type: String},
        levelAct13: {type: String},
        levelAct14: {type: String},
        levelAct15: {type: String},
        levelAct16: {type: String},
        levelAct17: {type: String},
        levelAct18: {type: String},
        levelAct19: {type: String},
        levelAct20: {type: String},
        participationHours: {type: String},
        participationCredit: {type: String},
        participationPaid: {type: String},
        allOut1: {type: Number},
        allOut2: {type: Number},
        allOut3: {type: Number},
        allOut4: {type: Number},
        allOut5: {type: Number},
        allOut6: {type: Number},
        allOut7: {type: Number},
        allOut8: {type: Number},
        allOut9: {type: Number},
        allOut10: {type: Number},
        allOut11: {type: Number},
        allOut12: {type: Number},
        allOut13: {type: Number},
        allOut14: {type: Number},
        allOut15: {type: Number},
        allOut16: {type: Number},
        allOut17: {type: Number},
        allOut18: {type: Number},
        allOut19: {type: Number},
        allOut20: {type: Number},
        allOut21: {type: Number},
        allOut22: {type: Number},
        allOut23: {type: Number},
        allOut24: {type: Number},
        allOut25: {type: Number},
        allOut26: {type: Number},
        allOut27: {type: Number},
        allOut28: {type: Number},
        allOut29: {type: Number},
        allOut30: {type: Number},
        allReason1: {type: Number},
        allReason2: {type: Number},
        allReason3: {type: Number},
        allReason4: {type: Number},
        allReason5: {type: Number},
        allReason6: {type: Number},
        allReason7: {type: Number},
        allReason8: {type: Number},
        allReason9: {type: Number},
        allReason10: {type: Number},
        allReason11: {type: Number},
        allReason12: {type: Number},
        allReason13: {type: Number},
        allReason14: {type: Number},
        allReason15: {type: Number},
        allReason16: {type: Number},
        allReason17: {type: Number},
        allReason18: {type: Number},
        allReason19: {type: Number},
        allReason20: {type: Number},
        allReason21: {type: Number},
        allReason22: {type: Number},
        allReason23: {type: Number},
        allReason24: {type: Number},
        allReason25: {type: Number},
        allReason26: {type: Number},
        allReason27: {type: Number},
        allReason28: {type: Number},
        allReason29: {type: Number},
        allReason30: {type: Number},
        topOut1: {type: Number},
        topOut2: {type: Number},
        topOut3: {type: Number},
        topOut4: {type: Number},
        topOut5: {type: Number},
        topOut6: {type: Number},
        topOut7: {type: Number},
        topOut8: {type: Number},
        topOut9: {type: Number},
        topOut10: {type: Number},
        topOut11: {type: Number},
        topOut12: {type: Number},
        topOut13: {type: Number},
        topOut14: {type: Number},
        topOut15: {type: Number},
        topOut16: {type: Number},
        topOut17: {type: Number},
        topOut18: {type: Number},
        topOut19: {type: Number},
        topOut20: {type: Number},
        topOut21: {type: Number},
        topOut22: {type: Number},
        topOut23: {type: Number},
        topOut24: {type: Number},
        topOut25: {type: Number},
        topOut26: {type: Number},
        topOut27: {type: Number},
        topOut28: {type: Number},
        topOut29: {type: Number},
        topOut30: {type: Number},
        topReason1: {type: Number},
        topReason2: {type: Number},
        topReason3: {type: Number},
        topReason4: {type: Number},
        topReason5: {type: Number},
        topReason6: {type: Number},
        topReason7: {type: Number},
        topReason8: {type: Number},
        topReason9: {type: Number},
        topReason10: {type: Number},
        topReason11: {type: Number},
        topReason12: {type: Number},
        topReason13: {type: Number},
        topReason14: {type: Number},
        loginRole: {type: String},
        loginEmail: {type: String},
        loginPassword: {type: String}
    }
});

// Before saving student into database, updates the updated_at and created_at (if student is new) 
studentSchema.pre('save', function(next) {
    const currentDate = new Date();
    this.updated_at = currentDate;
    if(!this.created_at){
      this.created_at = currentDate;
    }
    next();
});

const Student = mongoose.model('Student', studentSchema);

module.exports = Student;


